### ISSUE TITLE
idea 2020.3.2编译能通过,不能启动

### ISSUE THREAD

**Issue by zhengdewei94** [braisdom/ObjectiveSql#101]
我在使用idea 2020.3.2版本遇到的情况, compile, install都没问题,但是 build时异常,不能启动,. 直接使用java -jar  jar包能启动成功
异常信息:

`java: The class java.lang.IllegalArgumentException may be caused by the wrapped ProcessingEnvironment object.
  Please pass the wrapped ProcessingEnvironment further to super.init().
  If you need to access the original ProcessingEnvironment object (e.g. for creating com.sun.source.util.Trees.instance(ProcessingEnvironment)), you may use following code in the processor implementation:
  
  ProcessingEnvironment unwrappedprocessingEnv = jbUnwrap(ProcessingEnvironment.class, processingEnv);
  
  		where
  
  private static <T> T jbUnwrap(Class<? extends T> iface, T wrapper) {
    T unwrapped = null;
    try {
      final Class<?> apiWrappers = wrapper.getClass().getClassLoader().loadClass("org.jetbrains.jps.javac.APIWrappers");
      final Method unwrapMethod = apiWrappers.getDeclaredMethod("unwrap", Class.class, Object.class);
      unwrapped = iface.cast(unwrapMethod.invoke(null, iface, wrapper));
    }
    catch (Throwable ignored) {}
    return unwrapped != null? unwrapped : wrapper;
  }
`

**Comment by catchex** [comment]
同：https://github.com/braisdom/ObjectiveSql/issues/96，注意看里面的截图

**Comment by zhengdewei94** [comment]
添加了还是不行, 我原先使用的是2.3.6版本, 就算使用2.3.5版本也不行还是报错
![image](https://user-images.githubusercontent.com/32315862/106446814-ad0e7580-64bb-11eb-8d71-5d12821b8660.png)

**Comment by catchex** [comment]
仔细看一下那个issue，参数不是加在这里的。是加在Preferences/Compiler 里的

**Comment by zhengdewei94** [comment]
谢谢, 可以了
