### ISSUE TITLE
关于日期类型不能自动识别

### ISSUE THREAD

**Issue by zhengdewei94** [braisdom/ObjectiveSql#103]
我在 数据库字设置有日期类型, 但是插入的时候不能自动插入
![image](https://user-images.githubusercontent.com/32315862/106695468-9bd97c00-6615-11eb-9acb-1f167771a6ac.png)
![image](https://user-images.githubusercontent.com/32315862/106695530-c1668580-6615-11eb-9a6e-3a5753d733d8.png)
但是加了@Column注解就可以了,
![image](https://user-images.githubusercontent.com/32315862/106695617-e9ee7f80-6615-11eb-82f9-7058786353b9.png)

**Comment by catchex** [comment]
你需要配置一个Transition

```java
@Column(transition = SqlDateTimeTransition.class)
private Timestamp registeredAt;
```
