### ISSUE TITLE
请问 create保存数据的时候，为什么date类型的字段没有保存

### ISSUE THREAD

**Issue by forgottor** [braisdom/ObjectiveSql#105]
INSERT INTO `mee_join` (`join_id`,`meeting_id`,`user_id`,`join_type`,`status`) VALUES (?,?,?,?,?), with: [null,133,1,0,0]

meeJoin.setInTime(new Date());
 MeeJoin.create(meeJoin,true);

**Comment by catchex** [comment]
请参考：https://github.com/braisdom/ObjectiveSql/issues/103

**Comment by catchex** [comment]
如果问题已经解决，请关闭issue

**Comment by forgottor** [comment]
已解决 谢谢
