### ISSUE TITLE
请问关联查询如何设置固定只取部分字段

### ISSUE THREAD

**Issue by forgottor** [braisdom/ObjectiveSql#106]
SELECT * FROM `sys_user` WHERE user_id in (148,149,150)    目前只想取 select user_name, 用@Transient无效

 meeMeeting = MeeMeeting.queryFirst("mee_id = ?",
                     new Relationship[]{ MeeMeeting.HAS_MANY_MEE_CHATS,
                             MeeMeeting.HAS_MANY_SYS_FILE_INFOS,
                             MeeMeeting.HAS_MANY_MEE_JOINS,
                             MeeMeeting.HAS_MANY_MEE_VOTE_LIST,
                             **MeeMeeting.HAS_ONE_MAIN_USERS**
                     },
                     meeId);

    @Transient
    private String userName;

**Comment by catchex** [comment]
你好，这样的Case 应该属于自定义查询，基于Model 的查询，无法匹配不同的场景，进行不同的Projection, 你可以通过Select 类，自己构造Projection.

**Comment by forgottor** [comment]
请问rawAttributes 这个数据怎么隐藏，返回数据的时候全部取出来了

**Comment by catchex** [comment]
因为SQL 在Projection 时出现的字段，在Model 不一定都定义，例如：
```sql
select count(*) as user_count from users
```

user_count 字段在User 中未定义，它就会出现在rawAttributes 中，

**Comment by forgottor** [comment]
明白了谢谢
