### ISSUE TITLE
希望可以接入sqlhelper

### ISSUE THREAD

**Issue by fangjinuo** [braisdom/ObjectiveSql#18]
active record模式不错，有不少人喜欢。
是sqlhelper是一款强大的sql开发套件，支持分页、ddl dump，sql格式化等。这些功能都是独立于任何现有orm框架的，也是可以和他们无缝对接的。所以希望可以接入咱这款产品

**Comment by catchex** [comment]
当然可以，也是对objsql 的扩展性的挑战，有问题可以沟通，微信号：braisdom
