### ISSUE TITLE
是否可以把模块名和目录名保持一致

### ISSUE THREAD

**Issue by LuckZZ** [braisdom/ObjectiveSql#20]
在源码，是否可以把模块名和目录名保持一致，保持一致看着会舒服些

**Comment by catchex** [comment]
具体描述一下你的想法

**Comment by LuckZZ** [comment]
源码中，ObjectiveSql目录是funcsql模块(pom文件中定义的artifactId是funcsql)，建议模块名可以改为ObjectiveSql；core目录是objective-sql模块，建议目录名可以改为objective-sql。

**Comment by catchex** [comment]
是你，你的理解是正确的，funsql 是原有的名字，已经更新
