### ISSUE TITLE
插件显示数据类型和生成代码不一致

### ISSUE THREAD

**Issue by zifangshuo** [braisdom/ObjectiveSql#24]
使用中发现代码生成的ID的类型是long类型，IntelJ插件提示的数据类型是int类型。

**Comment by HawkinsBrus** [comment]
我也遇到了同样的问题，ObjectiveSQL IntelliJ plugin 1.2.5

```java
int memberCount = Member.countAll();
```
上述代码IntelliJ IDEA 没有提示错误，但编译的时候报：

`Member.countAll()` 返回的实际类型为java.lang.Long

**Comment by catchex** [comment]
已经修复了，请将ObjectiveSQL IntelliJ IDEA 插件更新至1.2.6
