### ISSUE TITLE
In gradle, package 'org.mangosdk.spi' does not exists

### ISSUE THREAD

**Issue by augustinexx** [braisdom/ObjectiveSql#26]
Could not find org.mangosdk.spi:spi:0.2.4.
Required by:
    project : > com.github.braisdom:objective-sql:1.3.6

How fix it

**Comment by catchex** [comment]
@augustinexx hi, gradle configuration likes below, because mangosdk.spi is in unofficial warehouse.
`
repositories {
    maven {
        url "https://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/"
    }
    mavenCentral()
}
`

**Comment by augustinexx** [comment]
thx

**Comment by augustinexx** [comment]
It is necessary to supplement the document

**Comment by catchex** [comment]
Thank you very much for your advice
