### ISSUE TITLE
跟lombok整合会出现lombok不好用

### ISSUE THREAD

**Issue by BruceLvLvXin** [braisdom/ObjectiveSql#28]
跟lombok整合会出现lombok不好用，但有时候好用，可能是编译顺序导致的吧

**Comment by catchex** [comment]
请提供更详细的信息，最好附上截图。我仔细验证了Lombok 和ObjectiveSQL 可以很好的结合

**Comment by catchex** [comment]
这个问题应该和 #30 一样，删除.idea 目录后重新打开项目，尝试一下
