### ISSUE TITLE
整合springboot报错哎， The connectionFactory cannot be null

### ISSUE THREAD

**Issue by BruceLvLvXin** [braisdom/ObjectiveSql#29]
2020-11-14 17:11:09.963  WARN 7360 --- [nio-8080-exec-6] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: java.lang.IllegalStateException: The connectionFactory cannot be null
这个错啥意思？不懂了

**Comment by catchex** [comment]
1）首先提问题要仔细，日志信息需要以代码的形式包裹前后用  "```"  包裹，
2）“ The connectionFactory cannot be null” 你可以参考：http://www.objsql.com/docs/basic/demo-source/ 这里的说明
![image](https://user-images.githubusercontent.com/875473/99147228-4ba7e900-26ba-11eb-9dfb-59d161b18a4e.png)
![image](https://user-images.githubusercontent.com/875473/99147236-5ebab900-26ba-11eb-89a4-0cdac287fa20.png)

**Comment by catchex** [comment]
ObjectiveSQL 全局注入你可以参考一下Databases.java 和Tables.java

**Comment by catchex** [comment]
如果已经修复了，请关闭issue ，如果还有疑问请回复。

**Comment by catchex** [comment]
我应该扩展一下SpringBoot， 实现AutoConfiguration，过两天会1.3.8 版本，会修复该问题。
