### ISSUE TITLE
Quickfix error

### ISSUE THREAD

**Issue by HawkinsBrus** [braisdom/ObjectiveSql#32]
我在execute 上进行Quckfix 操作, “Add throws on method"，生成的代码如下：
```java
    public static List<Order> queryOrders(String begin, String end, String[] memberNos)SQLSyntaxException
             {
        Order.Table order = Order.asTable();
        Member.Table member = Member.asTable();
        Select select = new Select();

        return select.execute(DatabaseType.MySQL, Order.class);
    }
```

很明显有问题，

**Comment by catchex** [comment]
请请提供IntelliJ IDEA 的完整版本信息和项目代码，感谢，这样有助我解决问题。

**Comment by HawkinsBrus** [comment]
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 8
Non-Bundled Plugins: com.github.braisdom.object-sql-intellij

**Comment by catchex** [comment]
这个问题应该和 #30 一样，删除.idea 目录后重新打开项目，尝试一下

**Comment by catchex** [comment]
跟踪很长时间，没有出现该错误，关闭
