### ISSUE TITLE
用了阿里的镜像报错，如图

### ISSUE THREAD

**Issue by augustinexx** [braisdom/ObjectiveSql#45]
![图片](https://user-images.githubusercontent.com/74344352/99864004-e6815580-2bdb-11eb-94f7-3b059828134d.png)

**Comment by catchex** [comment]
应该和阿里的镜像没有关系，我发布的 maven parent 没有发布，一个低级Bug

**Comment by catchex** [comment]
新版本已上传至中央库，你可以按README 调整一下版本。
