### ISSUE TITLE
我调整了一下objective_sql/core 下的代码，再跑单元测试报错

### ISSUE THREAD

**Issue by augustinexx** [braisdom/ObjectiveSql#46]
报错如下：
```
java: 服务配置文件不正确, 或构造处理程序对象javax.annotation.processing.Processor: Provider com.github.braisdom.objsql.apt.DomainModelCodeGenerator not found时抛出异常错误
```
<img width="830" alt="图片" src="https://user-images.githubusercontent.com/74344352/99865448-abcfeb00-2be4-11eb-9158-2facbcfc4963.png">

**Comment by catchex** [comment]
这个问题只有在基于ObjectiveSQL 源码开发时才会出现，我之前也经常遇到，只要Rebuild Project 一下就好了。
![image](https://user-images.githubusercontent.com/875473/99897150-13b02f80-2cd2-11eb-9674-bb2fd19fd2dd.png)
