### ISSUE TITLE
大佬，覆盖setId 方法，IDEA 报错。

### ISSUE THREAD

**Issue by AlbertaAllen** [braisdom/ObjectiveSql#62]
我要覆盖setId 方法，代码编译没问题，但IDEA 一直漂红呀。
<img width="521" alt="image" src="https://user-images.githubusercontent.com/74944689/100956000-8e8b0d00-3552-11eb-861b-2454c74c4d83.png">

**Comment by catchex** [comment]
已经在插件1.3.1修复
https://github.com/braisdom/ObjectiveSql-IntelliJ-Plugin/commit/dc30024212be445baebc91f8cf2ce0cc86c59347
