### ISSUE TITLE
Hi, 关于sql.Select 内的limit, offset 问题

### ISSUE THREAD

**Issue by HawkinsBrus** [braisdom/ObjectiveSql#63]
据我所知，limit, offset 只有MySQL 和SQLite 两种类型的数据库支持，Select 是一个能用的，放这两个语法在里面不太合适吧。

**Comment by catchex** [comment]
好问题.

**Comment by HawkinsBrus** [comment]
我觉得，标准API 的设计应该参考 ANSI 的标准，当然有些数据库不一定完全支持，但可以基于不同数据库进行扩展实现

**Comment by catchex** [comment]
同意你的想法
