### ISSUE TITLE
异常提示不准确

### ISSUE THREAD

**Issue by HawkinsBrus** [braisdom/ObjectiveSql#70]
我跟踪后发现是`MemberUser` 类没有增加 `DomainModel` Annotation，但异常信息如下：

<img width="560" alt="image" src="https://user-images.githubusercontent.com/176541/101305881-8e567e80-387e-11eb-889d-7b096a245216.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/176541/101305933-a5956c00-387e-11eb-96e1-2c177d126a78.png">

**Comment by catchex** [comment]
应该是内部逻辑判断有问题，错误的异常提醒的确会误导
