### ISSUE TITLE
感觉PrimaryKey 的设计比较诡异

### ISSUE THREAD

**Issue by augustinexx** [braisdom/ObjectiveSql#74]
1）为什么PrimaryKey 是通过DomainModel 设置的，不通过PrimaryKey Annotation 自定义呢？
2）我可以取消一个模型的主键吗？

**Comment by catchex** [comment]
你有什么好想法？

**Comment by catchex** [comment]
目前已经支持通过DomainModel 设置，也可以支持PrimaryKey 设置，1.4.4 版本修复
