### ISSUE TITLE
queryByPrimaryKey 报错

### ISSUE THREAD

**Issue by AlbertaAllen** [braisdom/ObjectiveSql#91]
类定义：

```java
@DomainModel
public class Order {
    @PrimaryKey
    private Integer orderId;
    private String no;
    private Integer memberId;
    private Double amount;
    private Double quantity;
    ...
}
```

<img width="647" alt="image" src="https://user-images.githubusercontent.com/74944689/102851568-28a9eb00-4457-11eb-8fe9-a71a7f4710b3.png">

**Comment by catchex** [comment]
https://github.com/braisdom/ObjectiveSql/commit/5c34d9d8247b5c3ca0ff74cf7db17db6bee14cd0
