### ISSUE TITLE
自定义主键后，拼接SQL 中总是包括“id” 字段

### ISSUE THREAD

**Issue by HawkinsBrus** [braisdom/ObjectiveSql#92]
```java
@DomainModel
public class Menu {

     @PrimaryKey
     private Integer menuId;
}
```

我已经自定义了主键”menuId”，拼接的SQL 如图：

![image](https://user-images.githubusercontent.com/176541/102873209-c7e0d980-447b-11eb-9349-339d5e82c00c.png)

**Comment by oliviaour** [comment]
这个问题是在生成主键代码时有问题。需要判断主键是否自定义。

**Comment by catchex** [comment]
在这次commit 中修复了： https://github.com/braisdom/ObjectiveSql/commit/5c34d9d8247b5c3ca0ff74cf7db17db6bee14cd0
