### ISSUE TITLE
Springboot 2.3.5 环境下报 java: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by sinowo** [braisdom/ObjectiveSql#96]
Executing pre-compile tasks...
Loading Ant configuration...
Running Ant tasks...
Too many modules require recompilation, forcing full project rebuild
Cleaning output directories...
Running 'before' tasks
Checking sources
Copying resources... [SpringAvue]
Parsing java... [SpringAvue]
java: java.lang.IllegalArgumentException
java: java.lang.IllegalArgumentException
javac 1.8.0_261 was used to compile java sources
Finished, saving caches...
Executing post-compile tasks...
Loading Ant configuration...
Running Ant tasks...
Synchronizing output directories...
2021/1/4 下午2:16 - Build completed with 2 errors and 0 warnings in 19 sec, 239 ms

---- 删除objsql-springboot库引用后正常跑起（JDK8.0）

**Comment by catchex** [comment]
你的IntelliJ IDEA 是2020.04 吧。之前我也遇到过这个问题，是IntelliJ 有个Bug
你增加配置：-Djps.track.ap.dependencies=false
IntelliJ Bug: https://youtrack.jetbrains.com/issue/IDEA-256707

![image](https://user-images.githubusercontent.com/875473/103509039-328f0d80-4e9d-11eb-8a3b-78f846bab9d2.png)

**Comment by catchex** [comment]
你按上述配置就可以了。

**Comment by sinowo** [comment]
偿试过加入 -Djps.track.ap.dependencies=false
但仍然不行。

**Comment by catchex** [comment]
你的IntelliJ 版本多少？可以加我微信：braisdom，我远程帮你看一下
